//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JS.Shipment.UPS.UpsLabelRecovery
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1")]
    public partial class ErrorDetailType
    {

        private string severityField;

        private CodeType primaryErrorCodeField;

        private string minimumRetrySecondsField;

        private LocationType locationField;

        private CodeType[] subErrorCodeField;

        private AdditionalInfoType[] additionalInformationField;

        private ElementLevelInformationType1 elementLevelInformationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public CodeType PrimaryErrorCode
        {
            get
            {
                return this.primaryErrorCodeField;
            }
            set
            {
                this.primaryErrorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string MinimumRetrySeconds
        {
            get
            {
                return this.minimumRetrySecondsField;
            }
            set
            {
                this.minimumRetrySecondsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public LocationType Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubErrorCode", Order = 4)]
        public CodeType[] SubErrorCode
        {
            get
            {
                return this.subErrorCodeField;
            }
            set
            {
                this.subErrorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalInformation", Order = 5)]
        public AdditionalInfoType[] AdditionalInformation
        {
            get
            {
                return this.additionalInformationField;
            }
            set
            {
                this.additionalInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public ElementLevelInformationType1 ElementLevelInformation
        {
            get
            {
                return this.elementLevelInformationField;
            }
            set
            {
                this.elementLevelInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1")]
    public partial class CodeType
    {

        private string codeField;

        private string descriptionField;

        private string digestField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Digest
        {
            get
            {
                return this.digestField;
            }
            set
            {
                this.digestField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ElementIdentifierType", Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1")]
    public partial class ElementIdentifierType1
    {

        private string codeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ElementLevelInformationType", Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1")]
    public partial class ElementLevelInformationType1
    {

        private string levelField;

        private ElementIdentifierType1[] elementIdentifierField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ElementIdentifier", Order = 1)]
        public ElementIdentifierType1[] ElementIdentifier
        {
            get
            {
                return this.elementIdentifierField;
            }
            set
            {
                this.elementIdentifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1")]
    public partial class AdditionalCodeDescType
    {

        private string codeField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1")]
    public partial class AdditionalInfoType
    {

        private string typeField;

        private AdditionalCodeDescType[] valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Order = 1)]
        public AdditionalCodeDescType[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1")]
    public partial class LocationType
    {

        private string locationElementNameField;

        private string xPathOfElementField;

        private string originalValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string LocationElementName
        {
            get
            {
                return this.locationElementNameField;
            }
            set
            {
                this.locationElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string XPathOfElement
        {
            get
            {
                return this.xPathOfElementField;
            }
            set
            {
                this.xPathOfElementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string OriginalValue
        {
            get
            {
                return this.originalValueField;
            }
            set
            {
                this.originalValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class PickupDateRangeType
    {

        private string beginDateField;

        private string endDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string BeginDate
        {
            get
            {
                return this.beginDateField;
            }
            set
            {
                this.beginDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class TrackingCandidateType
    {

        private string trackingNumberField;

        private string destinationPostalCodeField;

        private string destinationCountryCodeField;

        private PickupDateRangeType pickupDateRangeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string TrackingNumber
        {
            get
            {
                return this.trackingNumberField;
            }
            set
            {
                this.trackingNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string DestinationPostalCode
        {
            get
            {
                return this.destinationPostalCodeField;
            }
            set
            {
                this.destinationPostalCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string DestinationCountryCode
        {
            get
            {
                return this.destinationCountryCodeField;
            }
            set
            {
                this.destinationCountryCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public PickupDateRangeType PickupDateRange
        {
            get
            {
                return this.pickupDateRangeField;
            }
            set
            {
                this.pickupDateRangeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class ImageType
    {

        private LabelImageFormatType imageFormatField;

        private string graphicImageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public LabelImageFormatType ImageFormat
        {
            get
            {
                return this.imageFormatField;
            }
            set
            {
                this.imageFormatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string GraphicImage
        {
            get
            {
                return this.graphicImageField;
            }
            set
            {
                this.graphicImageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class LabelImageFormatType
    {

        private string codeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class ReceiptType
    {

        private string hTMLImageField;

        private ImageType imageField;

        private string uRLField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string HTMLImage
        {
            get
            {
                return this.hTMLImageField;
            }
            set
            {
                this.hTMLImageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ImageType Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class LabelImageType
    {

        private LabelImageFormatType labelImageFormatField;

        private string graphicImageField;

        private string hTMLImageField;

        private string pDF417Field;

        private string internationalSignatureGraphicImageField;

        private string uRLField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public LabelImageFormatType LabelImageFormat
        {
            get
            {
                return this.labelImageFormatField;
            }
            set
            {
                this.labelImageFormatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string GraphicImage
        {
            get
            {
                return this.graphicImageField;
            }
            set
            {
                this.graphicImageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string HTMLImage
        {
            get
            {
                return this.hTMLImageField;
            }
            set
            {
                this.hTMLImageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string PDF417
        {
            get
            {
                return this.pDF417Field;
            }
            set
            {
                this.pDF417Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string InternationalSignatureGraphicImage
        {
            get
            {
                return this.internationalSignatureGraphicImageField;
            }
            set
            {
                this.internationalSignatureGraphicImageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class LabelResultsType
    {

        private string trackingNumberField;

        private LabelImageType labelImageField;

        private ReceiptType receiptField;

        private FormType formField;

        private string mailInnovationsTrackingNumberField;

        private LabelImageType mailInnovationsLabelImageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string TrackingNumber
        {
            get
            {
                return this.trackingNumberField;
            }
            set
            {
                this.trackingNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public LabelImageType LabelImage
        {
            get
            {
                return this.labelImageField;
            }
            set
            {
                this.labelImageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public ReceiptType Receipt
        {
            get
            {
                return this.receiptField;
            }
            set
            {
                this.receiptField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public FormType Form
        {
            get
            {
                return this.formField;
            }
            set
            {
                this.formField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string MailInnovationsTrackingNumber
        {
            get
            {
                return this.mailInnovationsTrackingNumberField;
            }
            set
            {
                this.mailInnovationsTrackingNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public LabelImageType MailInnovationsLabelImage
        {
            get
            {
                return this.mailInnovationsLabelImageField;
            }
            set
            {
                this.mailInnovationsLabelImageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class FormType
    {

        private FormImageType imageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public FormImageType Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class FormImageType
    {

        private ImageFormatCodeType imageFormatField;

        private string graphicImageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ImageFormatCodeType ImageFormat
        {
            get
            {
                return this.imageFormatField;
            }
            set
            {
                this.imageFormatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string GraphicImage
        {
            get
            {
                return this.graphicImageField;
            }
            set
            {
                this.graphicImageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class ImageFormatCodeType
    {

        private string codeField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class HVRImageType
    {

        private ImageFormatCodeType imageFormatField;

        private string graphicImageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ImageFormatCodeType ImageFormat
        {
            get
            {
                return this.imageFormatField;
            }
            set
            {
                this.imageFormatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string GraphicImage
        {
            get
            {
                return this.graphicImageField;
            }
            set
            {
                this.graphicImageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class HighValueReportType
    {

        private HVRImageType imageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public HVRImageType Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class ResponseImageDetailType
    {

        private ImageFormatCodeType imageFormatField;

        private string graphicImageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ImageFormatCodeType ImageFormat
        {
            get
            {
                return this.imageFormatField;
            }
            set
            {
                this.imageFormatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string GraphicImage
        {
            get
            {
                return this.graphicImageField;
            }
            set
            {
                this.graphicImageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class ResponseImageType
    {

        private ResponseImageDetailType imageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ResponseImageDetailType Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class ElementIdentifierType
    {

        private string codeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class ElementLevelInformationType
    {

        private string levelField;

        private ElementIdentifierType[] elementIdentifierField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ElementIdentifier", Order = 1)]
        public ElementIdentifierType[] ElementIdentifier
        {
            get
            {
                return this.elementIdentifierField;
            }
            set
            {
                this.elementIdentifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class DetailType
    {

        private string codeField;

        private string descriptionField;

        private ElementLevelInformationType elementLevelInformationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public ElementLevelInformationType ElementLevelInformation
        {
            get
            {
                return this.elementLevelInformationField;
            }
            set
            {
                this.elementLevelInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class CodeDescriptionType
    {

        private string codeField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class ResponseType
    {

        private CodeDescriptionType responseStatusField;

        private CodeDescriptionType[] alertField;

        private DetailType[] alertDetailField;

        private TransactionReferenceType transactionReferenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CodeDescriptionType ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Alert", Order = 1)]
        public CodeDescriptionType[] Alert
        {
            get
            {
                return this.alertField;
            }
            set
            {
                this.alertField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlertDetail", Order = 2)]
        public DetailType[] AlertDetail
        {
            get
            {
                return this.alertDetailField;
            }
            set
            {
                this.alertDetailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public TransactionReferenceType TransactionReference
        {
            get
            {
                return this.transactionReferenceField;
            }
            set
            {
                this.transactionReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class TransactionReferenceType
    {

        private string customerContextField;

        private string transactionIdentifierField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string CustomerContext
        {
            get
            {
                return this.customerContextField;
            }
            set
            {
                this.customerContextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string TransactionIdentifier
        {
            get
            {
                return this.transactionIdentifierField;
            }
            set
            {
                this.transactionIdentifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class LRUPSPremiumCareFormType
    {

        private string pageSizeField;

        private string printTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string PageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string PrintType
        {
            get
            {
                return this.printTypeField;
            }
            set
            {
                this.printTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class ReferenceNumberType
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class ReferenceValuesType
    {

        private ReferenceNumberType referenceNumberField;

        private string shipperNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ReferenceNumberType ReferenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ShipperNumber
        {
            get
            {
                return this.shipperNumberField;
            }
            set
            {
                this.shipperNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class LabelDeliveryType
    {

        private string labelLinkIndicatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string LabelLinkIndicator
        {
            get
            {
                return this.labelLinkIndicatorField;
            }
            set
            {
                this.labelLinkIndicatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class TranslateType
    {

        private string languageCodeField;

        private string dialectCodeField;

        private string codeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string LanguageCode
        {
            get
            {
                return this.languageCodeField;
            }
            set
            {
                this.languageCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string DialectCode
        {
            get
            {
                return this.dialectCodeField;
            }
            set
            {
                this.dialectCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class LabelStockSizeType
    {

        private string heightField;

        private string widthField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class LabelSpecificationType
    {

        private string hTTPUserAgentField;

        private LabelImageFormatType labelImageFormatField;

        private LabelStockSizeType labelStockSizeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string HTTPUserAgent
        {
            get
            {
                return this.hTTPUserAgentField;
            }
            set
            {
                this.hTTPUserAgentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public LabelImageFormatType LabelImageFormat
        {
            get
            {
                return this.labelImageFormatField;
            }
            set
            {
                this.labelImageFormatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public LabelStockSizeType LabelStockSize
        {
            get
            {
                return this.labelStockSizeField;
            }
            set
            {
                this.labelStockSizeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class RequestType
    {

        private string[] requestOptionField;

        private string subVersionField;

        private TransactionReferenceType transactionReferenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestOption", Order = 0)]
        public string[] RequestOption
        {
            get
            {
                return this.requestOptionField;
            }
            set
            {
                this.requestOptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string SubVersion
        {
            get
            {
                return this.subVersionField;
            }
            set
            {
                this.subVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public TransactionReferenceType TransactionReference
        {
            get
            {
                return this.transactionReferenceField;
            }
            set
            {
                this.transactionReferenceField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.ups.com/WSDL/XOLTWS/LBRecovery/v1.0", ConfigurationName = "JS.Shipment.UPS.UpsLabelRecovery.PortType")]
    public interface PortType
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://onlinetools.ups.com/webservices/ShipBinding/v1.1", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(JS.Shipment.UPS.UpsLabelRecovery.ErrorDetailType[]), Action = "http://onlinetools.ups.com/webservices/ShipBinding/v1.1", Name = "Errors", Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<JS.Shipment.UPS.UpsLabelRecovery.LabelRecoveryResponse1> ProcessLabelRecoveryAsync(JS.Shipment.UPS.UpsLabelRecovery.LabelRecoveryRequest1 request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurity
    {

        private UPSSecurityUsernameToken usernameTokenField;

        private UPSSecurityServiceAccessToken serviceAccessTokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public UPSSecurityUsernameToken UsernameToken
        {
            get
            {
                return this.usernameTokenField;
            }
            set
            {
                this.usernameTokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public UPSSecurityServiceAccessToken ServiceAccessToken
        {
            get
            {
                return this.serviceAccessTokenField;
            }
            set
            {
                this.serviceAccessTokenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityUsernameToken
    {

        private string usernameField;

        private string passwordField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityServiceAccessToken
    {

        private string accessLicenseNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string AccessLicenseNumber
        {
            get
            {
                return this.accessLicenseNumberField;
            }
            set
            {
                this.accessLicenseNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class LabelRecoveryRequest
    {

        private RequestType requestField;

        private LabelSpecificationType labelSpecificationField;

        private TranslateType translateField;

        private LabelDeliveryType labelDeliveryField;

        private string trackingNumberField;

        private string mailInnovationsTrackingNumberField;

        private ReferenceValuesType referenceValuesField;

        private LRUPSPremiumCareFormType uPSPremiumCareFormField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0", Order = 0)]
        public RequestType Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public LabelSpecificationType LabelSpecification
        {
            get
            {
                return this.labelSpecificationField;
            }
            set
            {
                this.labelSpecificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public TranslateType Translate
        {
            get
            {
                return this.translateField;
            }
            set
            {
                this.translateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public LabelDeliveryType LabelDelivery
        {
            get
            {
                return this.labelDeliveryField;
            }
            set
            {
                this.labelDeliveryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string TrackingNumber
        {
            get
            {
                return this.trackingNumberField;
            }
            set
            {
                this.trackingNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string MailInnovationsTrackingNumber
        {
            get
            {
                return this.mailInnovationsTrackingNumberField;
            }
            set
            {
                this.mailInnovationsTrackingNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public ReferenceValuesType ReferenceValues
        {
            get
            {
                return this.referenceValuesField;
            }
            set
            {
                this.referenceValuesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public LRUPSPremiumCareFormType UPSPremiumCareForm
        {
            get
            {
                return this.uPSPremiumCareFormField;
            }
            set
            {
                this.uPSPremiumCareFormField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0")]
    public partial class LabelRecoveryResponse
    {

        private ResponseType responseField;

        private string shipmentIdentificationNumberField;

        private ResponseImageType cODTurnInPageField;

        private FormType formField;

        private HighValueReportType highValueReportField;

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0", Order = 0)]
        public ResponseType Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ShipmentIdentificationNumber
        {
            get
            {
                return this.shipmentIdentificationNumberField;
            }
            set
            {
                this.shipmentIdentificationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public ResponseImageType CODTurnInPage
        {
            get
            {
                return this.cODTurnInPageField;
            }
            set
            {
                this.cODTurnInPageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public FormType Form
        {
            get
            {
                return this.formField;
            }
            set
            {
                this.formField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public HighValueReportType HighValueReport
        {
            get
            {
                return this.highValueReportField;
            }
            set
            {
                this.highValueReportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LabelResults", typeof(LabelResultsType), Order = 5)]
        [System.Xml.Serialization.XmlElementAttribute("TrackingCandidate", typeof(TrackingCandidateType), Order = 5)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LabelRecoveryRequest1
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
        public JS.Shipment.UPS.UpsLabelRecovery.UPSSecurity UPSSecurity;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0", Order = 0)]
        public JS.Shipment.UPS.UpsLabelRecovery.LabelRecoveryRequest LabelRecoveryRequest;

        public LabelRecoveryRequest1()
        {
        }

        public LabelRecoveryRequest1(JS.Shipment.UPS.UpsLabelRecovery.UPSSecurity UPSSecurity, JS.Shipment.UPS.UpsLabelRecovery.LabelRecoveryRequest LabelRecoveryRequest)
        {
            this.UPSSecurity = UPSSecurity;
            this.LabelRecoveryRequest = LabelRecoveryRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LabelRecoveryResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.ups.com/XMLSchema/XOLTWS/LBRecovery/v1.0", Order = 0)]
        public JS.Shipment.UPS.UpsLabelRecovery.LabelRecoveryResponse LabelRecoveryResponse;

        public LabelRecoveryResponse1()
        {
        }

        public LabelRecoveryResponse1(JS.Shipment.UPS.UpsLabelRecovery.LabelRecoveryResponse LabelRecoveryResponse)
        {
            this.LabelRecoveryResponse = LabelRecoveryResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface PortTypeChannel : JS.Shipment.UPS.UpsLabelRecovery.PortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class PortTypeClient : System.ServiceModel.ClientBase<JS.Shipment.UPS.UpsLabelRecovery.PortType>, JS.Shipment.UPS.UpsLabelRecovery.PortType
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public PortTypeClient() :
                base(PortTypeClient.GetDefaultBinding(), PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PortTypeClient(EndpointConfiguration endpointConfiguration) :
                base(PortTypeClient.GetBindingForEndpoint(endpointConfiguration), PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public PortTypeClient(string endpointUrl, System.TimeSpan timeout, string username, string password, EndpointConfiguration endpointConfiguration = EndpointConfiguration.Port)
           : base(PortTypeClient.GetBindingForEndpoint(endpointConfiguration, timeout), PortTypeClient.GetEndpointAddress(endpointUrl))
        {
            this.ChannelFactory.Credentials.UserName.UserName = username;
            this.ChannelFactory.Credentials.UserName.Password = password;
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JS.Shipment.UPS.UpsLabelRecovery.LabelRecoveryResponse1> JS.Shipment.UPS.UpsLabelRecovery.PortType.ProcessLabelRecoveryAsync(JS.Shipment.UPS.UpsLabelRecovery.LabelRecoveryRequest1 request)
        {
            return base.Channel.ProcessLabelRecoveryAsync(request);
        }

        public System.Threading.Tasks.Task<JS.Shipment.UPS.UpsLabelRecovery.LabelRecoveryResponse1> ProcessLabelRecoveryAsync(JS.Shipment.UPS.UpsLabelRecovery.UPSSecurity UPSSecurity, JS.Shipment.UPS.UpsLabelRecovery.LabelRecoveryRequest LabelRecoveryRequest)
        {
            JS.Shipment.UPS.UpsLabelRecovery.LabelRecoveryRequest1 inValue = new JS.Shipment.UPS.UpsLabelRecovery.LabelRecoveryRequest1();
            inValue.UPSSecurity = UPSSecurity;
            inValue.LabelRecoveryRequest = LabelRecoveryRequest;
            return ((JS.Shipment.UPS.UpsLabelRecovery.PortType)(this)).ProcessLabelRecoveryAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Port))
            {
                return new System.ServiceModel.EndpointAddress("https://wwwcie.ups.com/webservices/LBRecovery");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.Port);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PortTypeClient.GetEndpointAddress(EndpointConfiguration.Port);
        }

        public enum EndpointConfiguration
        {

            Port,
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration, System.TimeSpan timeout)
        {
            var binding = new System.ServiceModel.BasicHttpsBinding();
            if (endpointConfiguration == EndpointConfiguration.Port)
            {
                binding.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
                binding.Security.Mode = System.ServiceModel.BasicHttpsSecurityMode.Transport;

                var integerMaxValue = int.MaxValue;
                binding.MaxBufferSize = integerMaxValue;
                binding.MaxReceivedMessageSize = integerMaxValue;
                binding.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                binding.AllowCookies = true;

                binding.ReceiveTimeout = timeout;
                binding.SendTimeout = timeout;
                binding.OpenTimeout = timeout;
                binding.CloseTimeout = timeout;
            }
            return binding;
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(string endpointUrl)
        {
            if (!endpointUrl.StartsWith("https://"))
            {
                throw new System.UriFormatException("The endpoint URL must start with https://.");
            }
            return new System.ServiceModel.EndpointAddress(endpointUrl);
        }
    }
}
