using JS.Shipment.UPS.Contract.Data;

namespace JS.Shipment.UPS.Model
{
    public class PickupCancelRequest: IPickupCancelRequest
    {
        public RequestType Request { get; set; }
        /// <summary>
        /// Cancel pickup by Pickup Request Number (PRN).
        /// 01 = Account Number
        /// 02 = PRN
        /// Length: 2
        /// Required: Yes
        /// </summary>
        public string CancelBy { get; set; }
        /// <summary>
        /// The pickup request number (PRN) generated by UPS pickup system. Required if CancelBy = 02
        /// Length: 11
        /// Required: Cond
        /// </summary>
        public string PRN { get; set; }
    }
}
